Initial work on electra mobile
Electra-project/Electra-Mobile pull request #6
Opened 2018-06-09 06:45 UTC by durrab

Initial work for storing the encrypted device id after verifying from the back end - This is just for a demo and more work will start after API availability.

in the Demo we have.

1. Splash loading screen which navigates the user to Login or Registration Screen after validating the device id from back end which is spring boot which I am using for testing purpose.

2018-06-09 07:30 UTC, ivangabriele commented
Thank you @durrab and welcome here 🙂 !

I will check and test that today.

2018-06-10 10:10 UTC, ivangabriele commented
So first global notes:
- I don't know why it's not there but there should be an `.editorconfig` file making sure we keep some consistency among the text editors / IDEs. I see you are using Eclipse, there is a [plugin](https://marketplace.eclipse.org/node/2506426) to take it into account. We use the same rules among all projects: https://github.com/Electra-project/electra-desktop/blob/master/.editorconfig
- Be careful not to push your `.settings` & your `.env`. Add these paths to the gitignore. As for the `.env`, provide instead a `.env.sample` which is an empirical convention, so that you can add private data in you `.env` while sharing with contributors what env vars they need to set in order to contribute.

2018-06-10 10:23 UTC, ivangabriele requested changes

2018-06-10 10:23 UTC, ivangabriele commented on src/components/splash/SplashScreen.tsx
> +  currentAction(screenHeight: any){
Add a verb here like `renderCurrentAction()` for example.

2018-06-10 10:23 UTC, ivangabriele commented on src/components/splash/SplashScreen.tsx
> +  checkDeviceIdInStorage = async() => {
It's an implicit convention we have among projects but we try to avoid using fat arrows as class methods. Either make it a single function helper that you can put in a root "helpers" directory, or make it a (private) method.

2018-06-11 02:48 UTC, durrab commented on src/components/splash/SplashScreen.tsx
> +  currentAction(screenHeight: any){
@ivangabriele changed - Other than this I am using env to get the API url - I will change it to env.dev for developers so then can test using this command according to react native config.
https://github.com/luggit/react-native-config

2019-05-06 11:48 UTC, closed without merging